### ISSUE TITLE
Use of empty objects might not work with all languages

### ISSUE THREAD

**Issue by bbakerman** [graphql-cats/graphql-cats#14]
The spec says for example that if the parse: element is present then it indicates that only parsing should happen

```
    when:
      parse:
    then:
      passes:
```

I was using Jackson YAML support and if I map that into Java object like

```
public class When {

    @JsonProperty
    private Execute execute;
    @JsonProperty
    private Object parse;
    @JsonProperty
    private List<String> validate;

    public Optional<Execute> getExecute() {
        return Optional.ofNullable(execute);
    }

    public boolean isParse() {
        return Optional.ofNullable(parse).isPresent();
    }

    public Optional<List<String>> getValidate() {
        return Optional.ofNullable(validate);
    }
}
```

then the fact that the key is present (but null) is now lost since they ALL appear to be null.

This might be a Jackson / Java problem but I am not sure the simple presence in the yaml will work for other languages.

I think it would be better to use an actual value which means it is much more explicit.

```
    when:
      parse:true
    then:
      passes:true
```

I can work around the current situation by using the low level `Map` reading techniques and hence detect if a `parse` key is in the map even if its null.  But can you do this in Kotlin say or all other languages?

I would tighten it up by making it explicit.

**Comment by OlegIlyenko** [comment]
Sounds good! :+1: I updated all of the scenarios: https://github.com/graphql-cats/graphql-cats/commit/942634e559c500258f161b69824702a6108b659f
