### ISSUE TITLE
Consistent key types

### ISSUE THREAD

**Issue by matthewmueller** [graphql-cats/graphql-cats#17]
First of all, thanks for creating this project. I'm using it to make a better graphql server for Go. One thing I ran into is that the format doesn't always follow the readme.

For example in the Readme, there's `execute - Object - executes a query`, but in the YAML, I'm seeing: 

https://github.com/graphql-cats/graphql-cats/blob/master/scenarios/execution/Executor.yaml#L502
https://github.com/graphql-cats/graphql-cats/blob/master/scenarios/execution/Executor.yaml#L522

This ends up meaning that the `execute` type is `boolean | null | Object`

Could the format be adjusted to always use the same types?

**Comment by OlegIlyenko** [comment]
Good catch, fixed: https://github.com/graphql-cats/graphql-cats/commit/f5561165d556ce3c24abd356192fd3273fa55352

It's great to hear that you find it useful! We are currently trying to push this effort forward and discussed it already several times at GraphQL WG meetings. At the moment several implementations are trying to create drivers for these tests. Hopefully soon we will be able to figure out the right format for these tests and then implement more scenarios.

Would be really interesting to hear your thoughts on this project in general and about challenges you faced while implementing it for Go GraphQL implementation.
