### ISSUE TITLE
VariablesDefaultValueAllowed rule no longer exists

### ISSUE THREAD

**Issue by cjoudrey** [graphql-cats/graphql-cats#19]
👋😄

I'm working on adding support for `graphql-cats` to [`rmosolgo/graphql-ruby`](https://github.com/rmosolgo/graphql-ruby) and in the process I noticed that the `VariablesDefaultValueAllowed` rule no longer exists as of https://github.com/graphql/graphql-js/pull/1274.

I'm assuming that at some point we may want to remove [`scenarios/validation/VariablesDefaultValueAllowed.yaml`](https://github.com/graphql-cats/graphql-cats/blob/f5561165d556ce3c24abd356192fd3273fa55352/scenarios/validation/VariablesDefaultValueAllowed.yaml) as it specifically tests the `VariablesDefaultValueAllowed` validation rule.

Just opening this issue so we don't forget.

**Comment by OlegIlyenko** [comment]
Really glad to hear this! You are right, this validation was removed. Thanks for creating an issue for this.

I normally would suggest to create PR which removes it, but at the moment it is the only validation available. If we remove it, then there would be no validation test examples. So I would suggest to remove it, but at the same time also add another test for other existing validation. [`ScalarLeafs`](https://github.com/graphql/graphql-js/blob/master/src/validation/__tests__/ScalarLeafs-test.js) looks like a good candidate - it is quite small and simple validation. WDYT? Would you be interested in creating a PR for it?

**Comment by cjoudrey** [comment]
> If we remove it, then there would be no validation test examples. 

:100: Exactly my thoughts.

>  [`ScalarLeafs`](https://github.com/graphql/graphql-js/blob/4f92f55a74477fde3b00eb99f9a37f1ff2d1bd0d/src/validation/__tests__/ScalarLeafs-test.js) looks like a good candidate - it is quite small and simple validation. 

:+1: Yeah, that sounds perfect.

I'll open a PR to add a new scenario for this rule and remove the one for `VariablesDefaultValueAllowed`.
