### ISSUE TITLE
Discussion: Licence & Contributor Code of Conduct

### ISSUE THREAD

**Issue by OlegIlyenko** [graphql-cats/graphql-cats#2]
Since this project is a collaborative effort and it contains the source code in form of test descriptions, we need to decide on the licence and contributor code of conduct.

I'm not en expert in these topics, so I can't really give a good insight on what would be the most suitable for this project. My first intuition tells me that we should probably start with the same licence that [graphql-js](https://github.com/graphql/graphql-js/blob/master/LICENSE) uses. [graphql-java](https://github.com/graphql-java/graphql-java/blob/master/CODE_OF_CONDUCT.md) also has a nice contributor code of conduct, so maybe we can use it as well?

**Comment by joshprice** [comment]
I used the latest version of this http://contributor-covenant.org/ for https://github.com/graphql-elixir. It's a standard and we can track updates.

**Comment by joshprice** [comment]
I used BSD also and think that makes sense here too.

**Comment by joshprice** [comment]
Have added Contributor CoC 47da2fb038d526e4c0e7584e5eea692549bc2f4e and an unlicense b5ada7ac23590b2b728236430f3b4349e2010a14
