### ISSUE TITLE
Invalid union query

### ISSUE THREAD

**Issue by ruiaraujo** [graphql-cats/graphql-cats#28]
https://github.com/graphql-cats/graphql-cats/blob/959929230c9ee37f9899b0d6577086f83175f93a/scenarios/execution/UnionInterface.yaml#L98

I can't find in the spec the behaviour that this test encodes.

**Comment by cjoudrey** [comment]
You might be interested in the discussion in this issue: #26

**Comment by ruiaraujo** [comment]
Small world. 👍
